server.port=8080
spring.application.name=decentralized-ehr

# Web3j Configuration for Local Hardhat/Ganache
web3j.client-address=${RPC_URL:http://127.0.0.1:8545}
contract.address=${CONTRACT_ADDRESS:0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9}
wallet.private-key=${PRIVATE_KEY:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}

# Pinata API Keys (Dummy default for local testing)
pinata.api.key=${PINATA_API_KEY:40f1a4b6218857acb96a}
pinata.secret.api.key=${PINATA_SECRET_API_KEY:f87f2cf7dcdbc13845335e8b9748c9f0845b04cf6f9e566c3e90f816aa37fcbf}

# AES Key (Must be 32 bytes for AES-256)
aes.secret.key=${AES_SECRET_KEY:d04c28915dd68d156e04813e207168d2d87b3af164f614f2a506e9ec3e0171c0}
